[project]
name = "clip-interpretability-via-sae"
version = "0.1.0"
description = "This research project aims to understand CLIP failure modes via a mechanistic interpretability approach using sparce auto-encoders."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "transformers",
    "ipykernel",
    "pillow",
    "torch",
    "torchvision",
    "datasets",
    "dotenv",
    "huggingface-hub",
    "ipynbname",
    "matplotlib"
]
